// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Snippet struct {
	ID         string `json:"id"`
	Content    string `json:"content"`
	IsArchived bool   `json:"isArchived"`
	CreatedAt  string `json:"createdAt"`
}
