package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	database "one-phrase-log/db"
	"one-phrase-log/graph/model"
)

// CreateSnippet is the resolver for the createSnippet field.
func (r *mutationResolver) CreateSnippet(ctx context.Context, content string) (*model.Snippet, error) {

	// DBモデルの作成
	newSnippet := &database.Snippet{
		Content: content,
		IsArchived: false,
	}

	// DBに保存
	if err := database.Db.Create(newSnippet).Error; err != nil {
		return nil,err
	}
	
	return &model.Snippet{
		ID: fmt.Sprintf("%d",newSnippet.ID),
		Content: newSnippet.Content,
		IsArchived: newSnippet.IsArchived,
		CreatedAt: newSnippet.CreatedAt.Format("2006-01-02 15:04:05"),
	},nil
}

// UpdateSnippet is the resolver for the updateSnippet field.
func (r *mutationResolver) UpdateSnippet(ctx context.Context, id string, content string) (*model.Snippet, error) {
	var snippet database.Snippet

	// idからデータを取得
	if err := database.Db.First(&snippet, id).Error; err != nil {
		return nil, fmt.Errorf("snippet not found: %w", err)
	}

	snippet.Content = content
	// DBに保存
	if err := database.Db.Save(&snippet).Error; err != nil {
		return nil,err
	}

	return &model.Snippet{
		ID:fmt.Sprintf("%d",snippet.ID),
		Content: snippet.Content,
		IsArchived: snippet.IsArchived,
		CreatedAt: snippet.CreatedAt.Format("2006-01-02 15:04:05"),
	},nil
}

// ToggleArchive is the resolver for the toggleArchive field.
func (r *mutationResolver) ToggleArchive(ctx context.Context, id string) (*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: ToggleArchive - toggleArchive"))
}

// Snippets is the resolver for the snippets field.
func (r *queryResolver) Snippets(ctx context.Context) ([]*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: Snippets - snippets"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }