package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"one-phrase-log/graph/model"
)

// CreateSnippet is the resolver for the createSnippet field.
func (r *mutationResolver) CreateSnippet(ctx context.Context, content string) (*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: CreateSnippet - createSnippet"))
}

// UpdateSnippet is the resolver for the updateSnippet field.
func (r *mutationResolver) UpdateSnippet(ctx context.Context, id string, content string) (*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: UpdateSnippet - updateSnippet"))
}

// ToggleArchive is the resolver for the toggleArchive field.
func (r *mutationResolver) ToggleArchive(ctx context.Context, id string) (*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: ToggleArchive - toggleArchive"))
}

// Snippets is the resolver for the snippets field.
func (r *queryResolver) Snippets(ctx context.Context) ([]*model.Snippet, error) {
	panic(fmt.Errorf("not implemented: Snippets - snippets"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
